### ISSUE TITLE
Vue 3 example

### ISSUE THREAD

**Issue by MrSunshyne** [adbrosaci/vue-lang-router#3]
Hello, 

I realize this is kinda early, any chance to get an example of this working with [vue-router-next](https://github.com/vuejs/vue-router-next) and [vue-i18n-next](https://github.com/intlify/vue-i18n-next/) ?

Thanks for the amazing plugin !

**Comment by radek-altof** [comment]
Hi @MrSunshyne, some parts of the plugin might need to be rewritten, in order to accommodate for breaking changes in [vue-router-next](https://github.com/vuejs/vue-router-next) and [vue-i18n-next](https://github.com/intlify/vue-i18n-next/).

Right now there's no plan to implement these, until the plugin sees more usage (stars, npm downloads). I might take a look at it sooner, but it's a low priority. I'll let you know when I do.

**Comment by MrSunshyne** [comment]
thanks for the heads up @radek-altof.

The problem that this lib solves is very niche, yet for all those who need it, there's no easy alternative. I'll try to figure it out meanwhile. Hoping this gets more attention sooner though :D

**Comment by radek-altof** [comment]
Vue 3 compatible version is here! It's only a pre-release, but you can check it out in the [vue-3 branch](https://github.com/adbrosaci/vue-lang-router/tree/vue-3). Downloadable from `npm` as `vue-lang-router@next`.

:warning: [vue-i18n-next](https://github.com/intlify/vue-i18n-next/) is still in beta and this plugin may have some issues as well, but feel free to test...

**Comment by radek-altof** [comment]
:earth_africa: [Language Router](https://github.com/adbrosaci/vue-lang-router/tree/vue-3) for Vue 3 looks stable now, however I won't remove the `beta` label until [vue-i18n-next](https://github.com/intlify/vue-i18n-next/) is released.

[Vue CLI plugin](https://github.com/adbrosaci/vue-cli-plugin-lang-router) has been updated as well, so it's as simple as doing `vue add lang-router` in a Vue 3 project. It doesn't handle migration though, that needs to be done manually - see [documentation](https://github.com/adbrosaci/vue-lang-router/tree/vue-3#version-information) for more info.
